### ISSUE TITLE
Flash CC2530 ?

### ISSUE THREAD

**Issue by snakuzzo** [jmichault/flash_cc2531#14]
Hi, is it possible to flash a CC2530?
Flashing CC2530 with debugger I need to use also 3.3V pin...in your tutorial for CC2531 with Rpi 3.3V is not used.

**Comment by JaviElio** [comment]
I have tested it, and it also works with CC2530.
cc_chipid returns "a524"

**Comment by vladi4k** [comment]
Also works with Webee CC2530 + CC2591. You may have to try several times to flash and use extern 3.3V VCC not the Rpi 3.3V.

**Comment by renatothome** [comment]
Hi all! I was able to flash the CC2530+CC2591 using this program in **RPi Pi 3b+** both firmware's 1 coordinator and 2 routes, but now I`m unable to **re-flash** the board again in order to updated the firmware. It keeps showing "ffff" when I run ./cc_chipid. 

What I`ve tried:
- Run the steps using RPi Pi 3b+ (using several -m options "100", "200", "300")
- Run the steps using RPi Pi 3b+ and using an external 3.3v to power the board (using several -m options "100", "200", "300")
- Run the steps using RPi Pi 4b (8gb) (Updated wiringPi to 2.52, using several -m options "100", "200", "300")
- Run the steps using RPi Pi 4b (8gb) and using an external 3.3v to power the board. (using several -m options "100", "200", "300")

it keeps returning "ffff". 

Any clues what I can do differently to **re-flash** the board?

cheers!

**Comment by swimhero** [comment]
i do it well , and  when i let it work, it can not find the ttyACMO with the USB port

**Comment by Morphy99** [comment]
> Hi all! I was able to flash the CC2530+CC2591 using this program in **RPi Pi 3b+** both firmware's 1 coordinator and 2 routes, but now I`m unable to **re-flash** the board again in order to updated the firmware. It keeps showing "ffff" when I run ./cc_chipid.
> 
> What I`ve tried:
> 
> * Run the steps using RPi Pi 3b+ (using several -m options "100", "200", "300")
> * Run the steps using RPi Pi 3b+ and using an external 3.3v to power the board (using several -m options "100", "200", "300")
> * Run the steps using RPi Pi 4b (8gb) (Updated wiringPi to 2.52, using several -m options "100", "200", "300")
> * Run the steps using RPi Pi 4b (8gb) and using an external 3.3v to power the board. (using several -m options "100", "200", "300")
> 
> it keeps returning "ffff".
> 
> Any clues what I can do differently to **re-flash** the board?
> 
> cheers!

Did you find a solution to this? I was going to try this but I don't want to brick my CC2530.
