### ISSUE TITLE
wiringPi deprecated

### ISSUE THREAD

**Issue by rumoldus** [jmichault/flash_cc2531#29]
Hi, this project depends on wiringPi but that is no longer available. It cannot be installed anymore. So this flash software also will not run.
[Edit]
The instructions on zigbee2mqtt will not work, but this will:

cd /tmp
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb

So no issue, actually

**Comment by nobodyguy** [comment]
@rumoldus Keep a track of my fork - https://github.com/nobodyguy/flash_cc2531
I removed wiringPi dependency and replaced it with a standard libgpiod.
I'm still waiting for my CC2530 boards to arrive, so give me a week to be able to test my changes and push it.

**Comment by Caius-Bonus** [comment]
@nobodyguy , Thanks for porting this to libgpiod. This project might become difficult to use without compatibility with current raspberry pi os versions. 

This project is important to keep these Zigbee devices accessible to people without CC programmer and these cheap devices are important to allow for accessible development for zigbee devices. 

However, I tested it with a CC2531 on a RPI3B on Bookworm and with `./cc_chipid` I got: `ID = 0000` . I didn't look further into it yet, but it still seems to work with https://project-downloads.drogon.net/wiringpi-latest.deb on a RPI3B. Would you be open to debug this? If @jmichault is open to it, it would be great to merge this here.

**Comment by ignis32** [comment]
@nobodyguy  did your fork work for you? I had tried it on bookworm  64bit Pi 4,  on bookworm 32 bit Pi0, and I get 0000 chipid.

If it never worked even for you, probably it is something worth to mention in your repo.

-----
Wiring is okay, because on legacy bullseye 32bit pi0  with wiring pi package from here https://github.com/WiringPi/WiringPi/releases/download/2.61-1/wiringpi-2.61-1-armhf.deb  and original jmichault repo code  it started working.
